name: flake_build_preview

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
  workflow_dispatch:

jobs:
  nix_check_build:
    name: Nix Check and Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Setup Cachix
        uses: cachix/cachix-action@v16
        with:
          name: rishabh5321
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Run flake check
        run: nix flake check

      - name: Build zed-editor-preview-fhs
        run: nix build .#zed-editor-preview-fhs
