name: flake_build_preview_fhs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
  workflow_dispatch:

jobs:
  nix_check_build:
    name: Nix Check and Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            auto-optimise-store = true
            experimental-features = nix-command flakes
            max-jobs = auto
            download-buffer-size = 500000000

      - name: Setup Cachix
        uses: cachix/cachix-action@v16
        with:
          name: rishabh5321
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Run flake check
        run: nix flake check

      - name: Build zed-editor-preview-fhs
        id: build-zed-editor-preview-fhs
        run: nix build --no-substitute .#zed-editor-preview-fhs
